
BINDIR = ../../../test/bin

jsonsvg:
	$(BINDIR)/svg2json *.svg > svg.json

timemap:
	$(BINDIR)/sv2json *taps.txt > timemap-raw.json

timemapi:
	$(BINDIR)/sv2json -i *taps.txt > timemap-raw.json





